### ISSUE TITLE
cite

### ISSUE THREAD

**Issue by faroit** [yinruiqing/change_detection#1]
hi, how can I cite this work and the paper? Is it published somewhere?

**Comment by yinruiqing** [comment]
Hi, thank you for your attention to this work. We have submitted this paper to Interspeech 2017 and it has not been published. But we will put it to arxiv soon.

**Comment by faroit** [comment]
alright. Would be great if you could update the readme as soon at it's published or uploaded to arxiv.

**Comment by yinruiqing** [comment]
Hi, the bibtex citation has been updated to Readme file. We'll update the bibtex if it is published.
